### ISSUE TITLE
Question: why the list should be put in the chronological folder?

### ISSUE THREAD

**Issue by za** [JPCERTCC/Lucky-Visitor-Scam-IoC#1]
Hi there,

I am new in C2 things. I have a question. Why we need to write `ioc.txt` in the chronological folder? 

I can see that this URL `sickdarkheld.info` has been written down in `ioc.txt` on two separate dates:

* https://github.com/JPCERTCC/Lucky-Visitor-Scam-IoC/blob/main/2024/04/01/ioc.txt#L7
* https://github.com/JPCERTCC/Lucky-Visitor-Scam-IoC/blob/main/2024/04/30/ioc.txt#L3C1-L3C18

How is the use case using this `ioc.txt`?

Thanks.

**Comment by shu-tom** [comment]
The number of IoCs is huge, and blocking all of them with a Proxy or Firewall could slow down the performance of the device. Therefore, it is recommended to use only the most recent (e.g., one month) IoCs.
